name: Publish Documentation

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U setuptools wheel
          pip install -U -r requirements.txt
      - name: Build and deploy
        shell: bash -l {0}
        run: |
          mkdocs build
          mkdocs gh-deploy --force